import Foundation
// TODO get rid of the swift and reuse kotlin shared code! Also make sure it is trimmed down to only used constants
// Analytics event name constants
enum AnalyticsEvents {
    static let SCREEN_VIEW = "screen_view"
    static let TAB_SWITCH = "tab_switch"
    static let DAY_SELECT = "day_select"
    static let FAVORITE_ADD = "favorite_add"
    static let FAVORITE_REMOVE = "favorite_remove"
    static let CONTENT_VIEW = "content_view"
    static let FILTER_TOGGLE = "filter_toggle"
    static let FILTER_FAVORITES = "filter_favorites"
    static let PULL_REFRESH = "pull_refresh"
    static let SEARCH_QUERY = "search_query"
    static let NOTIFICATION_PREF_CHANGE = "notification_pref_change"
    static let NOTIFICATION_REQUEST = "notification_request"
    static let MEDIA_LINK_CLICK = "media_link_click"
    static let MAP_VIEW = "map_view"
    static let CONTENT_STATE = "content_state"
    static let DATA_SYNC = "data_sync"
    static let CACHE_HIT = "cache_hit"
    static let USER_ACTION = "user_action"
}

enum AnalyticsParameters {
    static let PARAM_SCREEN_NAME = "screen_name"
    static let PARAM_APP_STATE = "app_state"
    static let PARAM_TAB_NAME = "tab_name"
    static let PARAM_PREVIOUS_TAB = "previous_tab"
    static let PARAM_DAY_NUMBER = "day_number"
    static let PARAM_DAY_NAME = "day_name"
    static let PARAM_ENTITY_TYPE = "entity_type"
    static let PARAM_ENTITY_ID = "entity_id"
    static let PARAM_ENTITY_NAME = "entity_name"
    static let PARAM_CONTENT_TYPE = "content_type"
    static let PARAM_CONTENT_ID = "content_id"
    static let PARAM_FILTER_TYPE = "filter_type"
    static let PARAM_ENABLED = "enabled"
    static let PARAM_QUERY_LENGTH = "query_length"
    static let PARAM_HAS_RESULTS = "has_results"
    static let PARAM_PREF_TYPE = "pref_type"
    static let PARAM_GRANTED = "granted"
    static let PARAM_LINK_TYPE = "link_type"
    static let PARAM_URL = "url"
    static let PARAM_VIEW_TYPE = "view_type"
    static let PARAM_STATE = "state"
    static let PARAM_DURATION_MS = "duration_ms"
    static let PARAM_HIT = "hit"
    static let PARAM_ACTION_TYPE = "action_type"
    static let SUCCESS = "success"
    static let PARAM_ERROR_TYPE = "error_type"
}
